apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: devops-lab
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: devops-lab-app
        metrics_path: /metrics
        static_configs:
          - targets:
              - devops-lab-service.devops-lab.svc.cluster.local:80
