{
 "title": "DevOps Lab App",
 "description": "Dashboard basico para la app del laboratorio",
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (route) (http_requests_total)"
    }
   ]
  },
  {
   "title": "HTTP Request Duration p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket[1m])))"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  },
  {
   "title": "Process CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "process_cpu_seconds_total" }
   ]
  },
  {
   "title": "Application Up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "up" }
   ]
  }
 ]
}